'use strict';

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('genrePolice', {
  close: () => ipcRenderer.invoke('window:close'),
  minimize: () => ipcRenderer.invoke('window:minimize'),
  setUiScale: (value) => ipcRenderer.invoke('window:set-ui-scale', value),
  setLayoutMode: (value) => ipcRenderer.invoke('window:set-layout-mode', value),
  setStageOutput: (value) => ipcRenderer.invoke('window:set-stage-output', value),
  setSettingsOpen: (visible) => ipcRenderer.send('window:settings-visibility', visible === true),
  mediaControl: (action) => ipcRenderer.invoke('media:control', action),
  recaptureAudio: () => ipcRenderer.invoke('media:recapture'),
  prepareRecording: (payload) => ipcRenderer.invoke('recording:prepare', payload),
  appendRecordingChunk: (payload) => ipcRenderer.invoke('recording:append', payload),
  finishRecording: (payload) => ipcRenderer.invoke('recording:finish', payload),
  cancelRecording: (payload) => ipcRenderer.invoke('recording:cancel', payload),
  prepareSnapshot: () => ipcRenderer.invoke('snapshot:prepare'),
  captureSnapshot: (token) => ipcRenderer.invoke('snapshot:capture', token),
  updateRecordingControls: (payload) => ipcRenderer.send('recording-controls:update', payload),
  getDiagnosticsStatus: () => ipcRenderer.invoke('diagnostics:status'),
  reportRenderPerformance: (payload) => ipcRenderer.send('diagnostics:render-performance', payload),
  exportDiagnostics: (payload) => ipcRenderer.invoke('diagnostics:export', payload),
  exportGenreData: () => ipcRenderer.invoke('genre-data:export'),
  importGenreData: () => ipcRenderer.invoke('genre-data:import'),
  clearAudioGenreMemory: () => ipcRenderer.invoke('audio-genre-memory:clear'),
  checkForUpdates: () => ipcRenderer.invoke('update:check'),
  dismissUpdate: (version) => ipcRenderer.invoke('update:dismiss', version),
  openUpdatePage: (url) => ipcRenderer.invoke('update:open-release', url),
  openAppDownloadPage: () => ipcRenderer.invoke('update:open-release', ''),
  openVcRuntimeDownload: () => ipcRenderer.invoke('support:open-vc-runtime'),
  getConfig: () => ipcRenderer.invoke('config:get'),
  setConfig: (patch) => ipcRenderer.invoke('config:set', patch),
  setGenreCorrection: (genreId) => ipcRenderer.invoke('genre-correction:set', genreId),
  clearGenreCorrection: () => ipcRenderer.invoke('genre-correction:clear'),
  getGenreCandidates: () => ipcRenderer.invoke('genre-candidates:get'),
  setTemporaryGenre: (genreId) => ipcRenderer.invoke('genre-temporary:set', genreId),
  clearTemporaryGenre: () => ipcRenderer.invoke('genre-temporary:clear'),
  setDemo: (id) => ipcRenderer.invoke('demo:set', id),
  artworkFacePalette: (payload) => ipcRenderer.invoke('artwork:face-palette', payload),
  notifyAudioOutputDeviceChanged: (payload) => ipcRenderer.send('audio:output-device-changed', payload),
  submitRhythmAudio: (samples) => ipcRenderer.send('rhythm-model:audio', samples),
  submitGenreAudio: (samples) => ipcRenderer.send('audio-genre-model:audio', samples),
  onNowPlaying: (callback) => ipcRenderer.on('now-playing', (_event, payload) => callback(payload)),
  onPlaybackTick: (callback) => ipcRenderer.on('playback-tick', (_event, payload) => callback(payload)),
  onLyrics: (callback) => ipcRenderer.on('lyrics-update', (_event, payload) => callback(payload)),
  onInteractionState: (callback) => ipcRenderer.on('interaction-state', (_event, payload) => callback(payload)),
  onUiScale: (callback) => ipcRenderer.on('ui-scale', (_event, payload) => callback(payload)),
  onLayoutMode: (callback) => ipcRenderer.on('layout-mode', (_event, payload) => callback(payload)),
  onStageOutputState: (callback) => ipcRenderer.on('stage-output-state', (_event, payload) => callback(payload)),
  onMediaSources: (callback) => ipcRenderer.on('media-sources', (_event, payload) => callback(payload)),
  onDemoTheme: (callback) => ipcRenderer.on('demo-theme', (_event, payload) => callback(payload)),
  onRestartAudio: (callback) => ipcRenderer.on('restart-audio', callback),
  onRhythmModel: (callback) => ipcRenderer.on('rhythm-model', (_event, payload) => callback(payload)),
  onLocalGenreModelStatus: (callback) => ipcRenderer.on('local-genre-model-status', (_event, payload) => callback(payload)),
  onBackdropProfile: (callback) => ipcRenderer.on('backdrop-profile', (_event, payload) => callback(payload)),
  onOpenSettings: (callback) => ipcRenderer.on('settings:open', callback),
  onOpenGenreCorrection: (callback) => ipcRenderer.on('genre-correction:open', callback),
  onRecordingCommand: (callback) => ipcRenderer.on('recording-command', (_event, command) => callback(command)),
  onRecordingControlsActivity: (callback) => ipcRenderer.on('recording-controls:activity', (_event, phase) => callback(phase)),
  onUpdateStatus: (callback) => ipcRenderer.on('update-status', (_event, payload) => callback(payload))
});
