const test = require('node:test');
const assert = require('node:assert/strict');

test('major genre particles use different spatial motion languages', async () => {
  const { genreMotionProfile } = await import('../renderer/genre-motion.mjs');
  assert.equal(genreMotionProfile({ mode: 'hardcore' }).flow, 'radial');
  assert.equal(genreMotionProfile({ mode: 'house' }).flow, 'orbit');
  assert.equal(genreMotionProfile({ mode: 'drum-bass' }).flow, 'warp');
  assert.equal(genreMotionProfile({ mode: 'trap' }).flow, 'fall');
  assert.equal(genreMotionProfile({ mode: 'trance' }).flow, 'inward');
  assert.equal(genreMotionProfile({ mode: 'future-bass' }).flow, 'rise');
  assert.equal(genreMotionProfile({ mode: 'latin' }).flow, 'orbit');
});

test('hard families and soft families do not share the same particle material', async () => {
  const { genreMotionProfile, genreParticleCount } = await import('../renderer/genre-motion.mjs');
  assert.equal(genreMotionProfile({ mode: 'metal' }).kind, 'spark');
  assert.equal(genreMotionProfile({ id: 'puzzycore', mode: 'hardcore' }).kind, 'spark');
  assert.equal(genreMotionProfile({ mode: 'hardstyle' }).kind, 'chevron');
  assert.equal(genreMotionProfile({ mode: 'future-bass' }).kind, 'bubble');
  assert.equal(genreMotionProfile({ id: 'happy-hardcore', mode: 'hardcore' }).kind, 'orb');
  assert.equal(genreMotionProfile({ id: 'k-pop', mode: 'pop' }).flow, 'orbit');
  assert.equal(genreMotionProfile({ id: 'k-pop', mode: 'pop' }).kind, 'sparkle');
  assert.equal(genreMotionProfile({ id: 'phonk', mode: 'phonk' }).kind, 'dust');
  assert.equal(genreMotionProfile({ id: 'drift-phonk', mode: 'phonk' }).kind, 'spark');
  assert.equal(genreMotionProfile({ id: 'uk-garage', mode: 'garage' }).flow, 'lateral');
  assert.equal(genreMotionProfile({ id: 'two-step-garage', mode: 'garage' }).kind, 'bead');
  assert.equal(genreMotionProfile({ id: 'future-garage', mode: 'garage' }).kind, 'mote');
  assert.equal(genreMotionProfile({ id: 'bassline', mode: 'garage' }).kind, 'block');
  assert.equal(genreParticleCount({ mode: 'metal' }, 0.2), 0);
  assert.ok(genreParticleCount({ mode: 'metal' }, 0.95) > genreParticleCount({ mode: 'house' }, 0.95));
});

test('impact contours inherit each family directional language', async () => {
  const { genreImpactRadiusRatio } = await import('../renderer/genre-motion.mjs');
  const dubstepSide = genreImpactRadiusRatio({ mode: 'dubstep' }, 0, 1);
  const dubstepTop = genreImpactRadiusRatio({ mode: 'dubstep' }, Math.PI / 2, 1);
  const bassMusicSide = genreImpactRadiusRatio({ id: 'bass-music', mode: 'dubstep' }, 0, 1);
  const bassMusicTop = genreImpactRadiusRatio({ id: 'bass-music', mode: 'dubstep' }, Math.PI / 2, 1);
  const trapBottom = genreImpactRadiusRatio({ mode: 'trap' }, Math.PI / 2, 1);
  const trapTop = genreImpactRadiusRatio({ mode: 'trap' }, -Math.PI / 2, 1);
  const tranceSide = genreImpactRadiusRatio({ mode: 'trance' }, 0, 1);
  const tranceTop = genreImpactRadiusRatio({ mode: 'trance' }, Math.PI / 2, 1);
  const houseLobe = genreImpactRadiusRatio({ id: 'house', mode: 'house' }, 0, 1);
  const futureHouseLobe = genreImpactRadiusRatio({ id: 'future-house', mode: 'house' }, 0, 1);
  const futureHouseValley = genreImpactRadiusRatio({ id: 'future-house', mode: 'house' }, Math.PI / 8, 1);
  const bassHouseLobe = genreImpactRadiusRatio({ id: 'bass-house', mode: 'house' }, 0, 1);
  const bassHouseValley = genreImpactRadiusRatio({ id: 'bass-house', mode: 'house' }, Math.PI / 8, 1);
  const bigRoomLobe = genreImpactRadiusRatio({ id: 'big-room-house', mode: 'house' }, 0, 1);
  const bigRoomValley = genreImpactRadiusRatio({ id: 'big-room-house', mode: 'house' }, Math.PI / 8, 1);
  const kawaiiEar = genreImpactRadiusRatio({ id: 'kawaii-bass', mode: 'kawaii-bass' }, -Math.PI / 2 - 0.72, 1);
  const kawaiiCrown = genreImpactRadiusRatio({ id: 'kawaii-bass', mode: 'kawaii-bass' }, -Math.PI / 2, 1);
  const kawaiiSide = genreImpactRadiusRatio({ id: 'kawaii-bass', mode: 'kawaii-bass' }, 0, 1);
  const phonkBass = genreImpactRadiusRatio({ id: 'phonk', mode: 'phonk' }, Math.PI / 2, 1);
  const phonkTop = genreImpactRadiusRatio({ id: 'phonk', mode: 'phonk' }, -Math.PI / 2, 1);
  const driftBell = genreImpactRadiusRatio({ id: 'drift-phonk', mode: 'phonk' }, 0, 1);
  const phonkBell = genreImpactRadiusRatio({ id: 'phonk', mode: 'phonk' }, 0, 1);
  const ukGaragePocket = genreImpactRadiusRatio({ id: 'uk-garage', mode: 'garage' }, 0, 1);
  const futureGaragePocket = genreImpactRadiusRatio({ id: 'future-garage', mode: 'garage' }, 0, 1);
  const basslinePocket = genreImpactRadiusRatio({ id: 'bassline', mode: 'garage' }, 0, 1);
  const latinBody = genreImpactRadiusRatio({ id: 'latin', mode: 'latin' }, 0, 1);
  const latinHand = genreImpactRadiusRatio({ id: 'latin', mode: 'latin' }, 0.72 / 5, 1);
  assert.ok(dubstepSide > dubstepTop);
  assert.ok(Math.min(bassMusicSide, bassMusicTop) > 1.015);
  assert.ok(Math.abs(bassMusicSide - bassMusicTop) < Math.abs(dubstepSide - dubstepTop));
  assert.ok(trapBottom > trapTop);
  assert.ok(tranceSide > tranceTop);
  assert.ok(futureHouseLobe > houseLobe);
  assert.ok(futureHouseLobe > futureHouseValley);
  assert.ok(bassHouseLobe > bassHouseValley);
  assert.ok(bassHouseLobe > houseLobe);
  assert.ok(bigRoomLobe > houseLobe);
  assert.ok(bigRoomLobe > bigRoomValley);
  assert.ok(kawaiiEar > kawaiiCrown);
  assert.ok(kawaiiEar > kawaiiSide);
  assert.ok(phonkBass > phonkTop);
  assert.ok(driftBell > phonkBell);
  assert.ok(ukGaragePocket > 1);
  assert.ok(basslinePocket > ukGaragePocket);
  assert.ok(ukGaragePocket > futureGaragePocket);
  assert.ok(latinBody > 1.008);
  assert.notEqual(latinBody, latinHand);
});
