export const fallbackTheme = {
  id: 'unknown', family: 'unknown', parent: 'ANALYZING', label: 'UNKNOWN',
  font: '"Orbitron"', accent: '#67f7ff', accent2: '#8d76ff', hot: '#ffffff',
  mode: 'electronic', energy: 0.86
};

export const demoTracks = {
  asmr: ['ASMR', 'Soft Rain · Ear to Ear', 'Moonlit ASMR'],
  bilibili: ['BILIBILI', 'Creator Video · Community Feed', 'Web Player'],
  'happy-hardcore': ['HAPPY HC', 'Rainbow Evidence', 'S3RL'],
  'uk-hardcore': ['UK HARDCORE', 'Electric Horizon', 'Gammer'],
  gabber: ['GABBER', 'Raise & Revolt', 'Genre Police Unit'],
  frenchcore: ['FRENCHCORE', 'Liberté du Kick', 'Genre Police Unit'],
  'uptempo-hardcore': ['UPTEMPO', '200 BPM Evidence', 'Genre Police Unit'],
  puzzycore: ['PUZZYCORE', 'Greazy Pink Evidence', 'GPF'],
  hardcore: ['HARDCORE', 'Case No. 909', 'Genre Police Unit'],
  hardstyle: ['HARDSTYLE', 'Reverse Bass Warrant', 'Genre Police Unit'],
  rawstyle: ['RAWSTYLE', 'Distorted Statement', 'Genre Police Unit'],
  'euphoric-hardstyle': ['EUPHORIC', 'Above the Kick', 'Genre Police Unit'],
  house: ['HOUSE', 'Four on the Floor', 'Genre Police Unit'],
  'deep-house': ['DEEP HOUSE', 'Afterhours', 'Genre Police Unit'],
  'tech-house': ['TECH HOUSE', 'Groove Evidence', 'Genre Police Unit'],
  'progressive-house': ['PROGRESSIVE', 'Endless Build', 'Genre Police Unit'],
  'bass-house': ['BASS HOUSE', 'Low End Suspect', 'Genre Police Unit'],
  'future-house': ['FUTURE HOUSE', 'Elastic Stabs', 'Genre Police Unit'],
  'electro-house': ['ELECTRO HOUSE', 'Voltage District', 'Genre Police Unit'],
  complextro: ['COMPLEXTRO', 'Circuit Acrobatics', 'Wolfgang Gartner'],
  'big-room-house': ['BIG ROOM', 'Mainstage Evidence', 'W&W'],
  amapiano: ['AMAPIANO', 'Log Drum Motion', 'Genre Police Unit'],
  'dutch-house': ['DUTCH HOUSE', 'Dirty Statement', 'Afrojack'],
  'fidget-house': ['FIDGET HOUSE', 'Crooked Groove', 'Crookers'],
  'melbourne-bounce': ['MELBOURNE BOUNCE', 'Elastic Floor', 'Will Sparks'],
  'acid-house': ['ACID HOUSE', '303 Testimony', 'DJ Pierre'],
  'tropical-house': ['TROPICAL HOUSE', 'Coastal Signal', 'Kygo'],
  'french-house': ['FRENCH HOUSE', 'Filtered Alibi', 'Daft Punk'],
  'disco-house': ['DISCO HOUSE', 'Mirrorball Case', 'Purple Disco Machine'],
  'hard-house': ['HARD HOUSE', 'Trade Floor', 'Lisa Lashes'],
  'future-bass': ['FUTURE BASS', 'Prismatic Hearts', 'Genre Police Unit'],
  'kawaii-bass': ['KAWAII BASS', 'Nyan Nyan Evidence!', "Snail's House"],
  dubstep: ['DUBSTEP', 'Bass Interrogation', 'Genre Police Unit'],
  moombahcore: ['MOOMBAHCORE', 'Bangarang (feat. Sirah)', 'Skrillex'],
  brostep: ['BROSTEP', 'Growl Warrant', 'Skrillex'],
  riddim: ['RIDDIM', 'Quarter Note Crime', 'Genre Police Unit'],
  'future-riddim': ['FUTURE RIDDIM', 'Prism Grid', 'Genre Police Unit'],
  'colour-bass': ['COLOUR BASS', 'Chroma Impact', 'Chime'],
  deathstep: ['DEATHSTEP', 'Blackout Sentence', 'SVDDEN DEATH'],
  'melodic-dubstep': ['MELODIC DUBSTEP', 'Weightless Impact', 'Genre Police Unit'],
  'trap-edm': ['EDM TRAP', 'Subpoena', 'RL Grime'],
  'festival-trap': ['FESTIVAL TRAP', 'Mainstage Snare', 'Flosstradamus'],
  'hybrid-trap': ['HYBRID TRAP', 'Cross Examination', 'NGHTMRE'],
  'hard-trap': ['HARD TRAP', 'No Appeal', 'SAYMYNAME'],
  'midtempo-bass': ['MIDTEMPO BASS', '100 BPM Hazard', 'REZZ'],
  'glitch-hop': ['GLITCH HOP', 'Broken Circuit', 'KOAN Sound'],
  moombahton: ['MOOMBAHTON', '110 Degree Case', 'Dillon Francis'],
  'drum-bass': ['DRUM & BASS', '174 Pursuit', 'Genre Police Unit'],
  breakcore: ['BREAKCORE', 'Fracture Sequence', 'Genre Police Unit'],
  neurofunk: ['NEUROFUNK', 'Neural Chase', 'Genre Police Unit'],
  'liquid-dnb': ['LIQUID DNB', 'Blue Current', 'Netsky'],
  'dancefloor-dnb': ['DANCEFLOOR DNB', 'Run the Evidence', 'Sub Focus'],
  'jump-up-dnb': ['JUMP UP DNB', 'Bassline Suspect', 'Hedex'],
  drumstep: ['DRUMSTEP', 'Half-Time Pursuit', 'Fox Stevenson'],
  jungle: ['JUNGLE', 'Amen Dossier', 'Nia Archives'],
  trance: ['TRANCE', 'Tunnel Vision', 'Genre Police Unit'],
  psytrance: ['PSYTRANCE', 'Fractal Witness', 'Astrix'],
  'uplifting-trance': ['UPLIFTING TRANCE', 'Above the Clouds', 'Aly & Fila'],
  'progressive-trance': ['PROGRESSIVE TRANCE', 'Long Horizon', 'Above & Beyond'],
  'tech-trance': ['TECH TRANCE', 'Precision Lift', 'Bryan Kearney'],
  'hard-trance': ['HARD TRANCE', 'Acid Verdict', 'Scot Project'],
  techno: ['TECHNO', 'Warehouse Protocol', 'Genre Police Unit'],
  'hard-techno': ['HARD TECHNO', 'Redline Protocol', 'Sara Landry'],
  'acid-techno': ['ACID TECHNO', 'Corrosive Evidence', 'Regal'],
  'melodic-techno': ['MELODIC TECHNO', 'Afterlife File', 'Anyma'],
  'industrial-techno': ['INDUSTRIAL TECHNO', 'Factory Warrant', 'Paula Temple'],
  'minimal-techno': ['MINIMAL TECHNO', 'Negative Space', 'Robert Hood'],
  'uk-garage': ['UK GARAGE', 'Swing Statement', 'Sammy Virji'],
  'future-garage': ['FUTURE GARAGE', 'Rain Signal', 'Burial'],
  'speed-garage': ['SPEED GARAGE', 'Accelerated Groove', 'DJ Q'],
  'two-step-garage': ['2-STEP GARAGE', 'Missing Beat', 'Artful Dodger'],
  bassline: ['BASSLINE', 'Low End Lineup', 'Holy Goof'],
  breakbeat: ['BREAKBEAT', 'Broken Beat Report', 'Stanton Warriors'],
  'big-beat': ['BIG BEAT', 'Block Rocking Case', 'The Chemical Brothers'],
  'nu-disco': ['NU-DISCO', 'Mirror Signal', 'Chromeo'],
  'electro-swing': ['ELECTRO SWING', 'Brass Circuit', 'Caravan Palace'],
  'dance-pop': ['DANCE POP', 'Chrome Spotlight', 'Genre Police Unit'],
  'j-pop': ['J-POP', 'Neon Sakura', 'Genre Police Unit'],
  anime: ['ANIME', 'Opening Sequence', 'Genre Police Unit'],
  vocaloid: ['VOCALOID', 'Synthetic Heart', 'Genre Police Unit'],
  'pop-rock': ['POP ROCK', 'Anthem Evidence', 'Genre Police Unit'],
  alternative: ['ALTERNATIVE', 'Off-Centre Signal', 'Genre Police Unit'],
  'hip-hop': ['HIP-HOP', 'Low End Statement', 'Genre Police Unit'],
  'experimental-hip-hop': ['EXPERIMENTAL RAP', 'Unclassified Cadence', 'MC赵小六'],
  phonk: ['PHONK', 'Memphis Loop Evidence', 'DJ Smokey'],
  'drift-phonk': ['DRIFT PHONK', 'Night Run', 'Kordhell'],
  rnb: ['R&B', 'Velvet Frequency', 'Genre Police Unit'],
  'disco-funk': ['DISCO / FUNK', 'Mirrorball Evidence', 'Genre Police Unit'],
  jazz: ['JAZZ', 'Blue Note File', 'Genre Police Unit'],
  classical: ['CLASSICAL', 'Orchestral Dossier', 'Genre Police Unit'],
  latin: ['LATIN', 'Heat Signature', 'Genre Police Unit'],
  punk: ['PUNK', 'Three Chord Warrant', 'Genre Police Unit'],
  metal: ['METAL', 'Steel Testimony', 'Genre Police Unit'],
  metalcore: ['METALCORE', 'Breakdown Report', 'Genre Police Unit'],
  deathcore: ['DEATHCORE', 'Gravity Sentence', 'Genre Police Unit'],
  'industrial-metal': ['INDUSTRIAL METAL', 'Machine Witness', 'Genre Police Unit']
};
